CREATE TABLE DEPT (
DEPTNO NUMERIC(2) DEFAULT 99 NOT NULL,
DNAME VARCHAR(14),
PRIMARY KEY (DEPTNO),
UNIQUE (DNAME)
);

CREATE TABLE EMP (
EMPNO NUMERIC(4) NOT NULL,
ENAME VARCHAR(10),
JOB VARCHAR(9),
MGR NUMERIC(4),
HIREDATE DATE,
SAL NUMERIC(7,2),
COMM NUMERIC(7,2),
DEPTNO NUMERIC(2) NOT NULL,
PRIMARY KEY (EMPNO),
FOREIGN KEY (MGR) REFERENCES EMP(EMPNO),
FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);

INSERT INTO DEPT (DEPTNO, DNAME) VALUES (1, 'VENDAS');
INSERT INTO DEPT (DEPTNO, DNAME) VALUES (2, 'RH');

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (1, 'MANUEL', 'VENDEDOR', NULL, '04/12/1999', 2500, 400, 1);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (2, 'EVANDRO', 'GERENTE', 1, '08/03/1988', 3000, 200, 1);
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (3, 'GEOVANA', 'ATENDENTE', NULL, '02/05/1977', 1500, 100, 2);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(4, 'JOSE', 'VENDEDOR', NULL, '07/08/1976', 2000, 20, 1);

UPDATE EMP SET ENAME = 'PAULO JOSE' WHERE EMPNO = 4;

ALTER TABLE EMP MODIFY SAL DEFAULT 300;

UPDATE EMP SET COMM = SAL*(5/100);



